# Generated by Django 2.2.7 on 2019-11-22 17:39

from django.db import migrations, models
import vent_your_rent.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vent',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vent',
            name='image',
            field=models.ImageField(upload_to=vent_your_rent.api.models.generate_upload_destination_path),
        ),
    ]
