# Generated by Django 2.2.10 on 2020-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191125_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='tagAskedToMoveOut',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagCannotGetFurlough',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagCannotGetUC',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagCantMove',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagFullPay',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagIncomeFell',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagOvercrowded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagRentHolidayOrReduction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagUCDoesntCoverRent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tagUnfitToLiveIn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
