# Generated by Django 2.2.10 on 2020-05-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200511_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='tagAskedToMoveOut',
            new_name='AskedToMoveOut',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagCannotGetFurlough',
            new_name='CannotGetFurlough',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagCannotGetUC',
            new_name='CannotGetUC',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagCantMove',
            new_name='CantMove',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagFullPay',
            new_name='FullPay',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagIncomeFell',
            new_name='IncomeFell',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagOvercrowded',
            new_name='Overcrowded',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagRentHolidayOrReduction',
            new_name='RentHolidayOrReduction',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagUCDoesntCoverRent',
            new_name='UCDoesntCoverRent',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='tagUnfitToLiveIn',
            new_name='UnfitToLiveIn',
        ),
    ]
