# Generated by Django 2.2.10 on 2020-05-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200511_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='vent',
            name='emoji',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
