# Generated by Django 2.2.10 on 2020-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vent_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='HousingOK',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
